name: Update AkashGo Playlist

on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run AkashGo Playlist Generator
        env:
          FANTRU: ${{ secrets.FANTRU }}
          BLUECODEXX: ${{ secrets.BLUECODEXX }}
          BLUECODEXXSID: ${{ secrets.BLUECODEXXSID }}
          APPXID: ${{ secrets.APPXID }}
          AGAPPXID: ${{ secrets.AGAPPXID }}
          FILEV8: ${{ secrets.FILEV8 }}
          APITKU: ${{ secrets.APITKU }}
          AKGBSUR: ${{ secrets.AKGBSUR }}
        run: |
          echo "=== Running AkashGo Playlist Generator ==="
          python app.py
          echo "=== Script Finished ==="
          ls -l

      - name: Commit updated playlist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update playlist ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push
          fi
